// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheLegoProject.Models;

#nullable disable

namespace TheLegoProject.Migrations
{
    [DbContext(typeof(LegoDatabase2Context))]
    [Migration("20240411201037_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("TheLegoProject.Models.CustRecommendation", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("customer_ID");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<string>("Rec1")
                        .HasColumnType("TEXT")
                        .HasColumnName("Rec_1");

                    b.Property<string>("Rec2")
                        .HasColumnType("TEXT")
                        .HasColumnName("Rec_2");

                    b.Property<string>("Rec3")
                        .HasColumnType("TEXT")
                        .HasColumnName("Rec_3");

                    b.Property<string>("Rec4")
                        .HasColumnType("TEXT")
                        .HasColumnName("Rec_4");

                    b.Property<string>("Rec5")
                        .HasColumnType("TEXT")
                        .HasColumnName("Rec_5");

                    b.HasKey("CustomerId");

                    b.ToTable("Cust_Recommendation", (string)null);
                });

            modelBuilder.Entity("TheLegoProject.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("customer_ID");

                    b.Property<double?>("Age")
                        .HasColumnType("REAL")
                        .HasColumnName("age");

                    b.Property<string>("BirthDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("birth_date");

                    b.Property<string>("CountryOfResidence")
                        .HasColumnType("TEXT")
                        .HasColumnName("country_of_residence");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.HasKey("CustomerId");

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("TheLegoProject.Models.LineItem", b =>
                {
                    b.Property<int>("TransactionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("transaction_ID");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_ID");

                    b.Property<int?>("Qty")
                        .HasColumnType("INTEGER")
                        .HasColumnName("qty");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rating");

                    b.HasKey("TransactionId", "ProductId");

                    b.ToTable("LineItem", (string)null);
                });

            modelBuilder.Entity("TheLegoProject.Models.Order", b =>
                {
                    b.Property<int>("TransactionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("transaction_ID");

                    b.Property<double?>("Amount")
                        .HasColumnType("REAL")
                        .HasColumnName("amount");

                    b.Property<string>("Bank")
                        .HasColumnType("TEXT")
                        .HasColumnName("bank");

                    b.Property<string>("CountryOfTransaction")
                        .HasColumnType("TEXT")
                        .HasColumnName("country_of_transaction");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("customer_ID");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("DayOfWeek")
                        .HasColumnType("TEXT")
                        .HasColumnName("day_of_week");

                    b.Property<string>("EntryMode")
                        .HasColumnType("TEXT")
                        .HasColumnName("entry_mode");

                    b.Property<int?>("Fraud")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fraud");

                    b.Property<string>("ShippingAddress")
                        .HasColumnType("TEXT")
                        .HasColumnName("shipping_address");

                    b.Property<int?>("Time")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time");

                    b.Property<string>("TypeOfCard")
                        .HasColumnType("TEXT")
                        .HasColumnName("type_of_card");

                    b.Property<string>("TypeOfTransaction")
                        .HasColumnType("TEXT")
                        .HasColumnName("type_of_transaction");

                    b.HasKey("TransactionId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("TheLegoProject.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_ID");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("ImgLink")
                        .HasColumnType("TEXT")
                        .HasColumnName("img_link");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int?>("NumParts")
                        .HasColumnType("INTEGER")
                        .HasColumnName("num_parts");

                    b.Property<int?>("Price")
                        .HasColumnType("INTEGER")
                        .HasColumnName("price");

                    b.Property<string>("PrimaryColor")
                        .HasColumnType("TEXT")
                        .HasColumnName("primary_color");

                    b.Property<string>("SecondaryColor")
                        .HasColumnType("TEXT")
                        .HasColumnName("secondary_color");

                    b.Property<string>("Subcategory")
                        .HasColumnType("TEXT")
                        .HasColumnName("subcategory");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year");

                    b.HasKey("ProductId");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("TheLegoProject.Models.Recommendation", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_ID");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int?>("PopScore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pop_score");

                    b.Property<string>("Rec1")
                        .HasColumnType("TEXT")
                        .HasColumnName("rec_1");

                    b.Property<string>("Rec2")
                        .HasColumnType("TEXT")
                        .HasColumnName("rec_2");

                    b.Property<string>("Rec3")
                        .HasColumnType("TEXT")
                        .HasColumnName("rec_3");

                    b.Property<string>("Rec4")
                        .HasColumnType("TEXT")
                        .HasColumnName("rec_4");

                    b.Property<string>("Rec5")
                        .HasColumnType("TEXT")
                        .HasColumnName("rec_5");

                    b.HasKey("ProductId");

                    b.ToTable("Recommendation", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
